# Druid 配置
spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qg.enroll.model
  configuration.map-underscore-to-camel-case: true

logging:
  file: /root/enroll/mylog.log
#  pattern:
#    console: "%d - %msg%n"
#    level:
#  config: classpath:logback-spring.xml


server:
  port: 10011

  ssl:
    key-store: classpath:1862255_join.qgbaba.top.pfx
    key-store-type: PKCS12
    key-store-password: eUnq7U6w
